top_minimal:   
  asterisk: 1000                   # (*)   (все вище без знаку - ✓/↟)
  star: 588.34769                  # (★)
  double_percent: 441.67642        # (%%)  
  white_diamond: 328.52389         # (◇)   
  chess_pawn: 238.09599            # (♙)    
  dollar: 180.00708                # ($)   
  vertical_bar: 136.47385          # (|)  
  chess_bishop_black: 96.90712     # (♝)   
  caret: 73.98952                  # (^)    
  degree: 58.16463                 # (°)  
  dotted_circle: 44.80215          # (◌)  
  ball_number_one: 34.93667        # (❶)   
  square: 26.68295                 # (□)    
  equality: 20.59000               # (=)   
  down_arrow: 18.28               # (▼)   
  double_cross: 16.03500           # (╬)   
  chess_rook_black: 14.7        # (♜)  
  double_arrow: 13.45           # (⇔)   
  circled_one: 11.75            # (①)  
  triangle: 10.45               # (∆)  
  square_with_round_corners: 9.3 # (▣)  
  up_arrow: 8.1                # (↑)   
  square_with_triangle: 7.42921    # (◩)  
  diamond: 6.6                 # (◊)
  half_circle_right: 5.7       # (◐)    
  chess_bishop: 4.78107            # (♗)   
  hash: 4.08438                    # (#)   
  chess_rook: 3.35              # (♖)    
  chess_queen: 2.75             # (♕)   
  chess_knight_black: 2.33      # (♞)   
  chess_king: 1.85              # (♔)   
  black_circle: 1.47911            # (●)   
  chess_queen_black: 1.15230       # (♛)   
  bullseye: 0.95807                # (◉)    
  chess_knight: 0.75810            # (♘)    
  diamond_with_plus: 0.55       # (◈)    
  heart: 0.44                  # (♡)    
  backtick: 0.28                # (`)    
  black_diamond: 0.22           # (◆)   
  double_underscore: 0.125       # (__)   
  white_star: 0.081              # (☆)    
  four_pointed_star: 0.055       # (✦)   
  tilde: 0.044                   # (~)    
  ampersand: 0.028               # (&)    
  sun: 0.022                     # (☼)    
  flower: 0.0125                  # (❊)    
  double_exclamation: 0.00855      # (!!)   
  chess_king_black: 0.0055        # (♚)    
  diamond_with_dot: 0.003        # (❖)   
  plus: 0.0008                    # (+)

# Free patterns






default_limit: 0

threshold_price_for_percentage_change: 30  # $  
change_percents_before_threshold: 0.3  # %
change_percents_after_threshold: 0.2  # %


pause_between_runs: 0 # seconds


min_difference_percent_to_reduce_the_price_between_first_and_second: 15 # percents % Мінімальна відсоткова різниця для підтягування 
max_difference_percent_to_reduce_the_price_between_first_and_second: 100 # percents % Максимальна відсоткова різниця для підтягування 
min_max_change_first_position : 1.0  #  % на скільки відсотків ціна першого місця буде менша за друге після підтягування 

one_percent_reduce_percent_difference: 301 # percents % Різниця у відсотках з другим місцем на непопулярний товар
reduce_price_non_popular_item : 0.01  #  % На скільки відсотків зменшится ціна на непопулярний товар

position_for_change_pattern_if_owner_price_over_limit: 12
position_for_change_pattern_if_owner_price_under_limit: 11

max_limit_price_for_pull: 399  # $


delete_temp_folders: True #  Delete temp folders after each full run to offer_id.'False' or 'True' for change option

test_mode_logs: False  # Extend logs mode. True or False for change mode

owner : "Allbestfory"

ignore_competitors_for_asterisk: ["BogOdin_EG", "play1ife", "Mipa", "haihei", "lvgame", "ProPerfect", "DungeonBud", "Thrall", "FFXIVGilShop", "CNLTeam", "Haliber", "SunRise", "DionysusGod", "BoostRoom", "Exloot", "elmagnifico"] #
ignore_competitors_for_other_patterns: ["ProPerfect", "DungeonBud"] #


ignore_words: ["Recipe:", "Plans:", "Schematic:", "Formula:", "Pattern:"]

log_colors:
  info: 'cyan'  # блакитний для звичайного тексту
  change_price: 'yellow'  # користувацький рівень для рядків зі зміненою ціною
  warning: 'yellow'  # жовтий для виділених рядків
  error: 'white'  # червоний для помилок
  critical: 'red'  # червоний для помилок
  time: 'white'  #  для часу
  level: 'cyan'  # для рівня
  module: 'magenta'  #  для модуля
  funcName: 'green'  # для функції
  linenumber: 'magenta'  # для номера рядка

user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
platform: "Linux x86_64"

api_retries: 5
api_retry_delay: 1
config_minimal_purchase_qty: 2

