top_minimal:
  asterisk:
    char: '*'
    value: 1100.0
  star:
    char: ★
    value: 525.41218
  double_percent:
    char: '%%'
    value: 390.25469
  white_diamond:
    char: ◇
    value: 288.07
  chess_pawn:
    char: ♙
    value: 213.0
  dollar:
    char: $
    value: 159.0
  vertical_bar:
    char: '|'
    value: 118.78
  chess_bishop_black:
    char: ♝
    value: 86.9
  caret:
    char: ^
    value: 65.9
  degree:
    char: °
    value: 51.0
  dotted_circle:
    char: ◌
    value: 39.5
  ball_number_one:
    char: ❶
    value: 30.7
  square:
    char: □
    value: 24.2
  diamond_with_dot:
    char: ❖
    value: 19.85
  equality:
    char: '='
    value: 17.9
  chess_king_black:
    char: ♚
    value: 16.7
  down_arrow:
    char: ▼
    value: 15.4
  double_cross:
    char: ╬
    value: 14.0
  chess_rook_black:
    char: ♜
    value: 12.7
  double_arrow:
    char: ⇔
    value: 11.3
  circled_one:
    char: ①
    value: 10.0
  triangle:
    char: ∆
    value: 8.9
  square_with_round_corners:
    char: ▣
    value: 7.9
  up_arrow:
    char: ↑
    value: 7.0
  square_with_triangle:
    char: ◩
    value: 6.2
  diamond:
    char: ◊
    value: 5.6
  half_circle_right:
    char: ◐
    value: 4.8
  chess_bishop:
    char: ♗
    value: 4.1
  hash:
    char: '#'
    value: 3.45
  chess_rook:
    char: ♖
    value: 2.85
  chess_queen:
    char: ♕
    value: 2.33
  chess_knight_black:
    char: ♞
    value: 1.92
  chess_king:
    char: ♔
    value: 1.55
  black_circle:
    char: ●
    value: 1.24
  chess_queen_black:
    char: ♛
    value: 1.0
  bullseye:
    char: ◉
    value: 0.695871
  chess_knight:
    char: ♘
    value: 0.529254
  diamond_with_plus:
    char: ◈
    value: 0.42
  heart:
    char: ♡
    value: 0.297
  backtick:
    char: '`'
    value: 0.21
  black_diamond:
    char: ◆
    value: 0.1344717
  double_underscore:
    char: __
    value: 0.087
  white_star:
    char: ☆
    value: 0.0529254
  four_pointed_star:
    char: ✦
    value: 0.042
  tilde:
    char: '~'
    value: 0.0303831
  ampersand:
    char: '&'
    value: 0.0205
  sun:
    char: ☼
    value: 0.0127413
  flower:
    char: ❊
    value: 0.0088
  double_exclamation:
    char: '!!'
    value: 0.005
  plus:
    char: +
    value: 0.001
system:
  default_limit: 0
  threshold_price_for_percentage_change: 30
  change_percents_before_threshold: 0.4
  change_percents_after_threshold: 0.3
  pause_between_runs: 0
  min_difference_percent_to_reduce_the_price_between_first_and_second: 5
  max_difference_percent_to_reduce_the_price_between_first_and_second: 70
  min_max_change_first_position: 0.5
  one_percent_reduce_percent_difference: 201
  reduce_price_non_popular_item: 0.01
  position_for_change_pattern_if_owner_price_over_limit: 20
  position_for_change_pattern_if_owner_price_under_limit: 19
  max_limit_price_for_pull: 499
  delete_temp_folders: false
  test_mode_logs: false
  owner: Allbestfory
  ignore_competitors_for_asterisk:
  - BogOdin_EG
  - play1ife
  - Mipa
  - DealHub
  - PVPGOLD
  - GGsSellers
  - haihei
  - lvgame
  - Antic23
  - ProPerfect
  - DungeonBud
  - Thrall
  - FFXIVGilShop
  - CNLTeam
  - Haliber
  - SunRise
  - DionysusGod
  - BoostRoom
  - Exloot
  - elmagnifico
  ignore_competitors_for_other_patterns:
  - ProPerfect
  - HandFarm
  - DFFDDD
  ignore_words:
  - 'Recipe:'
  - 'Plans:'
  - 'Schematic:'
  - 'Formula:'
  - 'Pattern:'
  user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/138.0.0.0 Safari/537.36
  delay_minutes_between_cycles: 5
  platform: Linux
  seller_id: '5688923'
  threads_quantity: 20
  config_minimal_purchase_qty: 2
  api_retries: 40
  api_retry_delay: 20
log_colors:
  info: cyan
  change_price: yellow
  warning: yellow
  error: white
  critical: red
  time: white
  level: cyan
  module: magenta
  funcName: green
  linenumber: magenta
