top_minimal:
  asterisk: 1000.00000 # (*) (все вище без знаку - ✓/↟)
  ball_number_one: 534.03356 # (❶)
  double_exclamation: 368.49090 # (!!)
  star: 300.49471 # (★)
  double_percent: 222.28485 # (%%)
  white_diamond: 166.06800 # (◇)
  chess_pawn: 127.52857 # (♙)
  dollar: 96.56450 # ($)
  vertical_bar: 72.27441 # (|)
  chess_bishop_black: 55.08177 # (♝)
  caret: 40.64300 # (^)
  degree: 31.03030 # (°)
  dotted_circle: 23.59329 # (◌)
  flower: 18.85378 # (❊)
  four_pointed_star: 15.27143 # (✦)
  diamond_with_dot: 12.51347 # (❖)
  equality: 10.52079 # (=)
  chess_king_black: 9.05010 # (♚)
  down_arrow: 7.99280 # (▼)
  double_cross: 7.14890 # (╬)
  chess_rook_black: 6.35350 # (♜)
  double_arrow: 5.71230 # (⇔)
  circled_one: 5.06340 # (①)
  triangle: 4.46103 # (∆)
  square_with_round_corners: 3.89940 # (▣)
  up_arrow: 3.37560 # (↑)
  diamond: 2.89060 # (◊)
  half_circle_right: 2.45410 # (◐)
  chess_bishop: 2.10490 # (♗)
  hash: 1.81390 # (#)
  chess_rook: 1.54230 # (♖)
  chess_queen: 1.29010 # (♕)
  chess_knight_black: 1.07119 # (♞)
  chess_king: 0.87300 # (♔)
  black_circle: 0.71057 # (●)
  chess_queen_black: 0.56191 # (♛)
  bullseye: 0.43808 # (◉)
  chess_knight: 0.32827 # (♘)
  diamond_with_plus: 0.24636 # (◈)
  heart: 0.17937 # (♡)
  backtick: 0.12283 # (`)
  black_diamond: 0.08545 # (◆)
  ampersand: 0.06780 # (&)
  double_underscore: 0.05238 # (__)
  square: 0.04074 # (□)
  white_star: 0.03104 # (☆)
  plus: 0.02134 # (+)
  tilde: 0.01164 # (~)
  sun: 0.00097 # (☼)

# Free patterns
  square_with_triangle: 0.0 # (◩)







default_limit: 0

threshold_price_for_percentage_change: 40  # $  
change_percents_before_threshold: 0.3  # %
change_percents_after_threshold: 0.4  # %

min_difference_percent_to_reduce_the_price_between_first_and_second: 9 # percents % Мінімальна відсоткова різниця для підтягування 
max_difference_percent_to_reduce_the_price_between_first_and_second: 80 # percents % Максимальна відсоткова різниця для підтягування
min_max_change_first_position : 0.5  #  % на скільки відсотків ціна першого місця буде менша за друге після підтягування 

one_percent_reduce_percent_difference: 201 # percents % Різниця у відсотках з другим місцем на непопулярний товар
reduce_price_non_popular_item : 0.01  #  % На скільки відсотків зменшится ціна на непопулярний товар

position_for_change_pattern_if_owner_price_over_limit: 30
position_for_change_pattern_if_owner_price_under_limit: 30

max_limit_price_for_pull: 199  # $


delete_temp_folders: True #  Delete temp folders after each full run to offer_id.'False' or 'True' for change option

test_mode_logs: False  # Extend logs mode. True or False for change mode

owner : "Allbestfory"

ignore_competitors_for_asterisk: [] #
ignore_competitors_for_other_patterns: [] #
 

ignore_words: ["Recipe:", "Plans:", "Schematic:", "Formula:", "Pattern:"]

user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

log_colors:
  info: 'cyan'  # блакитний для звичайного тексту
  change_price: 'yellow'  # користувацький рівень для рядків зі зміненою ціною
  warning: 'yellow'  # жовтий для виділених рядків
  error: 'white'  # червоний для помилок
  critical: 'red'  # червоний для помилок
  time: 'white'  #  для часу
  level: 'cyan'  # для рівня
  module: 'magenta'  #  для модуля
  funcName: 'green'  # для функції
  linenumber: 'magenta'  # для номера рядка

delay_minutes_between_cycles: 5
platform: "Windows"
seller_id: "5688923"
threads_quantity: 20
config_minimal_purchase_qty: 2
api_retries: 10
api_retry_delay: 100

take_ignors_when_pulling_price: True